---
# -----------------------------------------------------
# rbenv
# -----------------------------------------------------
- name: check rbenv install
  shell: bash -lc "rbenv --version"
  register: rbenv_exists
  changed_when: no
  ignore_errors: yes

- name: rbenv clone
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /home/ec2-user/.rbenv
  when: rbenv_exists is failed

- name: install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build

- name: path for rbenv01
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: '"# For rbenv"'
  when: rbenv_exists is failed

- name: path for rbenv02
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
  when: rbenv_exists is failed

- name: eval rbenv init
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(~/.rbenv/bin/rbenv init -)"'
  when: rbenv_exists is failed

- name: reflect .bash_profile
  shell: bash -lc "source ~/.bash_profile"
  when: rbenv_exists is failed
# -----------------------------------------------------
# ruby
# -----------------------------------------------------
- name: Check ruby exists
  shell: bash -lc "rbenv versions | grep {{ ruby_version }}"
  register: ruby_exists
  changed_when: no
  ignore_errors: yes

- name: ruby install
  shell: bash -lc "rbenv install {{ ruby_version }}"
  when: ruby_exists is failed

- name: rbenv rehash
  shell: bash -lc "rbenv rehash"
  when: ruby_exists is failed

- name: set ruby version
  shell: bash -lc "rbenv global {{ ruby_version }}"
  when: ruby_exists is failed

# -----------------------------------------------------
# rails
# -----------------------------------------------------
- name: check rails install
  shell: bash -lc "gem list -e rails | grep {{ rails_version }}"
  register: rails_exists
  changed_when: no
  ignore_errors: yes

- name: rails install
  become_user: root
  gem: 
    name: rails
    version: "{{ rails_version }}"
    executable: "/home/ec2-user/.rbenv/shims/gem"
    user_install: no
  when: rails_exists is failed
