---
- name: remove mariadb
  become: yes
  yum:
    name: mariadb-server
    state: absent

- name: remove mysql-server
  become: yes
  yum:
    name: mysql-server
    state: absent

- name: import GPG-Key
  become: yes
  rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

- name: mysql install
  become: yes
  yum:
    name: 'https://repo.mysql.com//mysql80-community-release-el7-11.noarch.rpm'
    state: present

- name: install MySQL RPM package
  become: yes
  ansible.builtin.yum:
    name: "/tmp/mysql.rpm"
    state: present

- name: install mysql-community-devel and server
  become: yes
  yum:
    name:
      - mysql-community-devel
      - mysql-community-client
    state: present
