---
- name: remove mariadb
  become_user: root
  yum:
    name: mariadb-server
    state: absent

- name: remove mysql-server
  become_user: root
  yum:
    name: mysql-server
    state: absent

- name: mysql install
  become: true
  command: sudo yum localinstall -y https://dev.mysql.com/get/mysql80-community-release-el7-5.noarch.rpm

- name: import GPG-Key
  become_user: root
  rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
  when: mysql install.changed

- name: install mysql-community-devel and server
  become_user: root
  yum:
    name:
      - mysql-community-devel
      - mysql-community-server
    state: present
  when: mysql_installed.changed

- name: create database.yml
  become_user: root
  template:
    src: database.yml.j2
    dest: "{{ app_dir }}/config/database.yml"

