---
- name: remove MariaDB
  become: true
  yum:
    name: mariadb-server
    state: absent

- name: remove mysql-server
  become: yes
  yum:
    name: mysql-server
    state: absent

- name: import GPG-Key
  become: yes
  rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

- name: Install MySQL repository
  become: yes
  yum:
    name: 'https://repo.mysql.com//mysql80-community-release-el7-11.noarch.rpm'
    state: present


- name: install mysql-community-client
  become: yes
  yum:
    name: mysql-community-client
    state: present


- name: Install mysql-community-devel
  become: yes
  yum:
    name: mysql-community-devel
    state: present



