---
# -----------------------------------------------------
# app clone
# -----------------------------------------------------
- name: Create directory
  become: yes
  ansible.builtin.file:
    path: /var/www
    state: directory
    mode: "0755"
    owner: ec2-user

- name: Clone sample-app
  ansible.builtin.git:
    repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
    dest: "{{ app_dir }}"
    force: yes
  register: app_clone

- name: change app permission
  become: yes
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: ec2-user
    recurse: yes
  when: app_clone.changed

- name: bundle install
  shell: bash -lc "sudo {{ app_dir }} bundle install"
  when: app_clone.changed
  args: 
    chdir: "{{ app_dir }}"
# -----------------------------------------------------
# edit file
# -----------------------------------------------------


- name: edit puma.rb
  become: yes
  template:
    src: puma.rb.j2
    dest: "{{ app_dir }}/config/puma.rb"

- name: edit development.rb
  become: yes
  template:
    src: development.rb.j2
    dest: "{{ app_dir }}/config/environments/development.rb"

- name: edit storage.yml
  become: yes
  template:
    src: storage.yml.j2
    dest: "{{ app_dir }}/config/storage.yml"

- name: create database.yml
  become: yes
  template:
    src: database.yml.j2
    dest: "{{ app_dir }}/config/database.yml"

- name: bin/setup
  shell: |
    bash -lc "bin/setup"
  args: 
    chdir: "{{ app_dir }}"
  when: mysql_installed.changed

- name: asset precompile
  shell: |
    bash -lc "rails assets:precompile"
  args: 
    chdir: "{{ app_dir }}"
# -----------------------------------------------------
# system start
# -----------------------------------------------------
- name: start nginx
  become: yes
  service:
    name: nginx
    state: started
  register: nginx_started

- name: start puma
  become: yes
  service:
    name: puma
    state: started
  when: nginx_started.changed

- name: edit puma.service
  become: yes
  template:
    src: puma.service.j2
    dest: /etc/systemed/system/puma.service
    recurse: yes
