---
# -----------------------------------------------------
# app clone
# -----------------------------------------------------
- name: directory check
  stat:
    path: "{{ app_dir }}"
  register: app_dir_check


- name: clone sample-app
  ansible.builtin.git:
    repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
    dest: "{{ app_dir }}"
    force: yes
  register: app_clone
  when: app_dir_check.stat.exists == false

- name: change app permission
  become_user: root
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: ec2-user
    mode: "775"
    recurse: yes
  when: app_dir_check.changed

- name: bundle install
  become_user: root
  shell: bash -lc "bundle install"
  when: app_dir_check.stat.exists == false
  
- name: bin/setup
  shell: |
    bash -lc "bin/setup"
  when: app_dir_check.stat.exists == false

- name: asset precompile
  shell: |
    bash -lc "rails assets:precompile"
  when: app_dir_check.stat.exists == false
# -----------------------------------------------------
# edit file
# -----------------------------------------------------
- name: edit puma.service
  become_user: root
  template:
    src: puma.service.j2
    dest: /etc/systemed/system/puma.service

- name: edit puma.rb
  become_user: root
  template:
    src: puma.rb.j2
    dest: "{{ app_dir }}/config/puma.rb"

- name: edit development.rb
  become_user: root
  template:
    src: development.rb.j2
    dest: "{{ app_dir }}/config/environments/development.rb"

- name: edit storage.yml
  become_user: root
  template:
    src: storage.yml.j2
    dest: "{{ app_dir }}/config/storage.yml"
# -----------------------------------------------------
# system start
# -----------------------------------------------------
- name: start nginx
  become_user: root
  service:
    name: nginx
    state: started
  register: nginx_started

- name: start puma
  become_user: root
  service:
    name: puma
    state: started
  when: nginx_started.changed
