---
- name: check nginx exsits
  shell: bash -lc "nginx -v"
  register: nginx_exists
  changed_when: no
  ignore_errors: yes

- name: nginx install
  become: yes
  shell: bash -lc "amazon-linux-extras install -y nginx1"
  when: nginx_exists is failed

- name: create default.conf
  become: yes
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  when: nginx_exists is failed

- name: nginx permission
  become: yes
  file: 
    path: /var/lib
    state: directory
    mode: '0775'
    recurse: yes

