---
- name: check nginx install
  shell: bash -lc "nginx -v"
  register: nginx_exists
  changed_when: no
  ignore_errors: yes

- name: nginx install
  become_user: root
  shell: bash -lc "amazon-linux-extras install -y nginx1"
  when: nginx_exists is failed

- name: create nginc.conf
  become_user: root
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/nginx.conf
  when: nginx_exists is failed

- name: nginx permission
  become_user: root
  file: 
    path: /var/lib
    state: directory
    mode: '0775'
    recurse: yes

