- hosts: 175.41.242.116
  become: True
  become_user: ec2-user

  vars: 
    app_dir: /var/www/raisetech-live8-sample-app
    ruby_version: 3.2.3
    bundler_version: 2.3.14
    rails_version: 7.1.3.2
    node_version: 17.9.1

  roles:
    - { role: app, tags: app }
    - { role: rbenv, tags: rbenv }
    - { role: node, tags: node }
    - { role: yarn, tags: yarn }
    - { role: bundler, tags: bundler }
    - { role: nginx, tags: nginx }

