- hosts: 175.41.242.116
  become: True
  become_user: ec2-user

  vars: 
    app_dir: /var/www/raisetech-live8-sample-app

  roles:
    - { role: app, tags: app }
    - { role: rbenv, tags: rbenv }
    - { role: node, tags: node }
    - { role: yarn, tags: yarn }
    - { role: bundler, tags: bundler }
    - { role: nginx, tags: nginx }
